from _typeshed import Incomplete
from collections.abc import Callable
from typing import Any
from apscheduler.executors.asyncio import AsyncIOExecutor
from apscheduler.schedulers.base import BaseScheduler

def run_in_event_loop(func: Callable[..., Any]): ...

class AsyncIOScheduler(BaseScheduler):
  _eventloop: Incomplete
  _timeout: Incomplete
  def start(self, paused: bool = False) -> None: ...
  @run_in_event_loop
  def _shutdown(self, wait: bool = True) -> None: ...
  def shutdown(self, wait: bool = True) -> None: ...
  def _configure(self, config: dict[str, Any]) -> None: ...
  def _start_timer(self, wait_seconds: float) -> None: ...
  def _stop_timer(self) -> None: ...
  @run_in_event_loop
  def wakeup(self) -> None: ...
  def _create_default_executor(self) -> AsyncIOExecutor: ...  # type: ignore
