# Standard library imports
from abc import ABCMeta, abstractmethod
from collections.abc import Callable, Sequence
from datetime import datetime
from importlib.metadata import EntryPoint
from logging import Logger
from threading import RLock
from typing import Any, Literal, TextIO, TypedDict, overload

# Third party imports
from _typeshed import SupportsRead, SupportsWrite
from zoneinfo import ZoneInfo
from apscheduler.events import SchedulerEvent
from apscheduler.executors.base import BaseExecutor
from apscheduler.executors.pool import ThreadPoolExecutor
from apscheduler.job import Job
from apscheduler.jobstores.base import BaseJobStore
from apscheduler.jobstores.memory import MemoryJobStore
from apscheduler.triggers.base import BaseTrigger

STATE_STOPPED: int
STATE_RUNNING: int
STATE_PAUSED: int

class JobDefaults(TypedDict):
  misfire_grace_time: int | None
  coalesce: bool
  max_instances: int | None

class BaseScheduler(metaclass=ABCMeta):
  _trigger_plugins: dict[str, EntryPoint]
  _executor_plugins: dict[str, EntryPoint]
  _jobstore_plugins: dict[str, EntryPoint]
  _trigger_classes: dict[str, type[BaseTrigger]]
  _executor_classes: dict[str, type[BaseExecutor]]
  _jobstore_classes: dict[str, type[BaseJobStore]]
  _executors: dict[str, BaseExecutor]
  _executors_lock: RLock
  _jobstores: dict[str, BaseJobStore]
  _jobstores_lock: RLock
  _listeners: list[tuple[Callable[..., Any], int]]
  _listeners_lock: RLock
  _pending_jobs: list[tuple[Job, str, bool]]
  state: int
  def __init__(self, gconfig: dict[str, Any] = {}, **options) -> None: ...
  def __getstate__(self) -> None: ...
  def configure(self, gconfig: dict = {}, prefix: str = "apscheduler.", **options) -> None: ...
  def start(self, paused: bool = False) -> None: ...
  @abstractmethod
  def shutdown(self, wait: bool = True) -> None: ...
  def pause(self) -> None: ...
  def resume(self) -> None: ...
  @property
  def running(self): ...
  def add_executor(self, executor: str | BaseExecutor, alias: str = "default", **executor_opts) -> None: ...
  def remove_executor(self, alias: str, shutdown: bool = True) -> None: ...
  def add_jobstore(self, jobstore: str | BaseJobStore, alias: str = "default", **jobstore_opts) -> None: ...
  def remove_jobstore(self, alias: str, shutdown: bool = True) -> None: ...
  def add_listener(self, callback: Callable[[Any]], mask: int = ...) -> None: ...
  def remove_listener(self, callback: Callable[[Any]]) -> None: ...
  def add_job(
    self,
    func: Callable[..., Any],
    trigger: str | BaseTrigger = None,
    args: Sequence[Any] | None = None,
    kwargs: dict[str, Any] | None = None,
    id: str | None = None,  # noqa: A002
    name: str | None = None,
    misfire_grace_time: int = ...,
    coalesce: bool = ...,
    max_instances: int = ...,
    next_run_time: datetime = ...,
    jobstore: str = "default",
    executor: str = "default",
    replace_existing: bool = False,
    **trigger_args,
  ) -> Job: ...
  def scheduled_job[**P_T, R_T](
    self,
    trigger: str | BaseTrigger = None,
    args: Sequence[Any] | None = None,
    kwargs: dict[str, Any] | None = None,
    id: str | None = None,  # noqa: A002
    name: str | None = None,
    misfire_grace_time: int = ...,
    coalesce: bool = ...,
    max_instances: int = ...,
    next_run_time: datetime = ...,
    jobstore: str = "default",
    executor: str = "default",
    **trigger_args,
  ) -> Callable[[Callable[P_T, R_T]], Callable[P_T, R_T]]: ...
  def modify_job(self, job_id: str, jobstore: str | None = None, **changes) -> Job: ...
  def reschedule_job(
    self, job_id: str, jobstore: str | None = None, trigger: str | BaseTrigger | None = None, **trigger_args
  ) -> Job: ...
  def pause_job(self, job_id: str, jobstore: str | None = None) -> None: ...
  def resume_job(self, job_id: str, jobstore: str | None = None) -> None: ...
  def get_jobs(self, jobstore: str | None = None, pending: bool | None = None) -> list[Job]: ...
  def get_job(self, job_id: str, jobstore: str | None = None) -> tuple[Job, str | None]: ...
  def remove_job(self, job_id: str, jobstore: str | None = None) -> None: ...
  def remove_all_jobs(self, jobstore: str | None = None) -> None: ...
  def print_jobs(self, jobstore: str | None = None, out: TextIO | None = None) -> None: ...
  def export_jobs(self, outfile: SupportsWrite[str], jobstore: str | None = None) -> None: ...
  def import_jobs(self, infile: SupportsRead[str], jobstore: str = "default") -> None: ...
  @abstractmethod
  def wakeup(self): ...
  _logger: Logger
  timezone: ZoneInfo
  jobstore_retry_interval: float
  _job_defaults: JobDefaults
  def _configure(self, config: dict[str, Any]) -> None: ...
  def _create_default_executor(self) -> ThreadPoolExecutor: ...
  def _create_default_jobstore(self) -> MemoryJobStore: ...
  def _lookup_executor(self, alias: str) -> BaseExecutor: ...
  def _lookup_jobstore(self, alias: str) -> BaseJobStore: ...
  def _lookup_job(self, job_id: str, jobstore_alias: str) -> tuple[Job, str | None]: ...
  def _dispatch_event(self, event: SchedulerEvent) -> None: ...
  def _check_uwsgi(self) -> None: ...
  def _real_add_job(self, job: Job, jobstore_alias: str, replace_existing: bool) -> None: ...
  @overload
  def _create_plugin_instance(self, type_: Literal["trigger"], alias: str, constructor_kwargs: dict[str, Any]) -> BaseTrigger: ...
  @overload
  def _create_plugin_instance(self, type_: Literal["jobstore"], alias: str, constructor_kwargs: dict[str, Any]) -> BaseJobStore: ...
  @overload
  def _create_plugin_instance(self, type_: Literal["executor"], alias: str, constructor_kwargs: dict[str, Any]) -> BaseExecutor: ...
  def _create_plugin_instance(self, type_: str, alias: str, constructor_kwargs: dict[str, Any]): ...
  def _create_trigger(self, trigger: str | BaseTrigger, trigger_args: dict[str, Any]) -> BaseTrigger: ...
  def _create_lock(self) -> RLock: ...
  def _process_jobs(self) -> None | float: ...
