from _typeshed import Incomplete
from apscheduler.schedulers.base import BaseScheduler

class BlockingScheduler(BaseScheduler):
  _event: Incomplete
  def start(self, *args, **kwargs) -> None: ...
  def shutdown(self, wait: bool = True) -> None: ...
  def _main_loop(self) -> None: ...
  def wakeup(self) -> None: ...
