from _typeshed import Incomplete
from apscheduler.schedulers.blocking import BlockingScheduler

class GeventScheduler(BlockingScheduler):
  _greenlet: Incomplete
  _event: Incomplete
  def start(self, *args, **kwargs): ...
  def shutdown(self, *args, **kwargs) -> None: ...
  def _create_lock(self): ...
  def _create_default_executor(self): ...
