from _typeshed import Incomplete
from apscheduler.schedulers.base import BaseScheduler

qtcore: Incomplete
QTimer: Incomplete

class QtScheduler(BaseScheduler):
  _timer: Incomplete
  def shutdown(self, *args, **kwargs) -> None: ...
  def _start_timer(self, wait_seconds) -> None: ...
  def _stop_timer(self) -> None: ...
  def wakeup(self) -> None: ...
  def _process_jobs(self) -> None: ...
