from _typeshed import Incomplete
from apscheduler.schedulers.base import BaseScheduler

def run_in_ioloop(func): ...

class TornadoScheduler(BaseScheduler):
  _ioloop: Incomplete
  _timeout: Incomplete
  @run_in_ioloop
  def _shutdown(self, wait: bool = True) -> None: ...
  def shutdown(self, wait: bool = True) -> None: ...
  def _configure(self, config) -> None: ...
  def _start_timer(self, wait_seconds) -> None: ...
  def _stop_timer(self) -> None: ...
  def _create_default_executor(self): ...
  @run_in_ioloop
  def wakeup(self) -> None: ...
