from _typeshed import Incomplete
from apscheduler.schedulers.base import BaseScheduler

def run_in_reactor(func): ...

class TwistedScheduler(BaseScheduler):
  _reactor: Incomplete
  _delayedcall: Incomplete
  def _configure(self, config) -> None: ...
  @run_in_reactor
  def _shutdown(self, wait: bool = True) -> None: ...
  def shutdown(self, wait: bool = True) -> None: ...
  def _start_timer(self, wait_seconds) -> None: ...
  def _stop_timer(self) -> None: ...
  @run_in_reactor
  def wakeup(self) -> None: ...
  def _create_default_executor(self): ...
