# Standard library imports
from collections.abc import Callable, Coroutine
from datetime import date, datetime, timedelta, timezone, tzinfo
from functools import partial
from typing import Any, Literal, overload
from zoneinfo import ZoneInfo

# Third party imports
from _typeshed import ConvertibleToInt

__all__ = [
  "asbool",
  "asint",
  "astimezone",
  "check_callable_args",
  "convert_to_datetime",
  "datetime_ceil",
  "datetime_to_utc_timestamp",
  "get_callable_name",
  "localize",
  "maybe_ref",
  "normalize",
  "obj_to_ref",
  "ref_to_obj",
  "undefined",
  "utc_timestamp_to_datetime",
]

class _Undefined:
  def __nonzero__(self) -> Literal[False]: ...
  def __bool__(self) -> Literal[False]: ...

undefined: _Undefined

def asint(text: ConvertibleToInt) -> int | None: ...
def asbool(obj: str | object) -> bool: ...
def astimezone(obj: ZoneInfo | timezone | str | tzinfo) -> ZoneInfo | timezone: ...
@overload
def asdate(obj: str) -> date: ...
@overload
def asdate[T](obj: T) -> T: ...
def asdate(obj): ...
def convert_to_datetime(
  input: None | datetime | date | str,  # noqa: A002
  tz: str | timezone | ZoneInfo | tzinfo,
  arg_name: str,
) -> datetime | None: ...
def datetime_to_utc_timestamp(timeval): ...
def utc_timestamp_to_datetime(timestamp): ...
def timedelta_seconds(delta): ...
def datetime_ceil(dateval): ...
def datetime_utc_add(dateval: datetime, tdelta: timedelta) -> datetime: ...
def datetime_repr(dateval): ...
def timezone_repr(timezone: tzinfo) -> str: ...
def get_callable_name(func): ...
def obj_to_ref(obj): ...
def ref_to_obj(ref): ...
def maybe_ref(ref): ...
def check_callable_args(func, args, kwargs) -> None: ...
def iscoroutinefunction_partial(f: partial | Callable[..., Coroutine[Any, Any, Any]]) -> bool: ...
def normalize(dt: datetime) -> datetime: ...
def localize(dt: datetime, tzinfo: timezone | ZoneInfo | tzinfo) -> datetime: ...
