from _typeshed import Incomplete
from abc import ABCMeta, abstractmethod
from datetime import datetime
from logging import Logger

from apscheduler.job import Job
from apscheduler.schedulers.base import BaseScheduler

class JobLookupError(KeyError):
  def __init__(self, job_id: str) -> None: ...

class ConflictingIdError(KeyError):
  def __init__(self, job_id: str) -> None: ...

class TransientJobError(ValueError):
  def __init__(self, job_id: str) -> None: ...

class BaseJobStore(metaclass=ABCMeta):
  _scheduler: BaseScheduler
  _alias: str
  _logger: Logger
  _jobs: list[tuple[Job, int]]
  def start(self, scheduler: BaseScheduler, alias: str) -> None: ...
  def shutdown(self) -> None: ...
  def _fix_paused_jobs_sorting(self, jobs: list[Job]) -> None: ...
  @abstractmethod
  def lookup_job(self, job_id: str) -> Job | None: ...
  @abstractmethod
  def get_due_jobs(self, now: datetime): ...
  @abstractmethod
  def get_next_run_time(self): ...
  @abstractmethod
  def get_all_jobs(self) -> list[Job]: ...
  @abstractmethod
  def add_job(self, job: Job) -> None: ...
  @abstractmethod
  def update_job(self, job: Job) -> None: ...
  @abstractmethod
  def remove_job(self, job_id: str): ...
  @abstractmethod
  def remove_all_jobs(self): ...
  def __repr__(self) -> str: ...
