from _typeshed import Incomplete
from apscheduler.jobstores.base import BaseJobStore as BaseJobStore, ConflictingIdError as ConflictingIdError, JobLookupError as JobLookupError
from apscheduler.util import datetime_to_utc_timestamp as datetime_to_utc_timestamp

class MemoryJobStore(BaseJobStore):
    _jobs: Incomplete
    _jobs_index: Incomplete
    def __init__(self) -> None: ...
    def lookup_job(self, job_id): ...
    def get_due_jobs(self, now): ...
    def get_next_run_time(self): ...
    def get_all_jobs(self): ...
    def add_job(self, job) -> None: ...
    def update_job(self, job) -> None: ...
    def remove_job(self, job_id) -> None: ...
    def remove_all_jobs(self) -> None: ...
    def shutdown(self) -> None: ...
    def _get_job_index(self, timestamp, job_id): ...
