from _typeshed import Incomplete
from apscheduler.job import Job
from apscheduler.jobstores.base import BaseJobStore

class SQLAlchemyJobStore(BaseJobStore):
  pickle_protocol: Incomplete
  engine: Incomplete
  jobs_t: Incomplete
  def __init__(
    self,
    url=None,
    engine=None,
    tablename: str = "apscheduler_jobs",
    metadata=None,
    pickle_protocol=...,
    tableschema=None,
    engine_options=None,
  ) -> None: ...
  def start(self, scheduler, alias) -> None: ...
  def lookup_job(self, job_id): ...
  def get_due_jobs(self, now): ...
  def get_next_run_time(self): ...
  def get_all_jobs(self): ...
  def add_job(self, job) -> None: ...
  def update_job(self, job) -> None: ...
  def remove_job(self, job_id) -> None: ...
  def remove_all_jobs(self) -> None: ...
  def shutdown(self) -> None: ...
  def _reconstitute_job(self, job_state): ...
  def _get_jobs(self, *conditions): ...
  def __repr__(self) -> str: ...
