from _typeshed import Incomplete
from abc import ABCMeta, abstractmethod
from datetime import datetime
from types import TracebackType
from apscheduler.events import (
  EVENT_JOB_ERROR as EVENT_JOB_ERROR,
  EVENT_JOB_EXECUTED as EVENT_JOB_EXECUTED,
  EVENT_JOB_MISSED as EVENT_JOB_MISSED,
  JobExecutionEvent as JobExecutionEvent,
)
from apscheduler.job import Job
from apscheduler.schedulers.base import BaseScheduler

class MaxInstancesReachedError(Exception):
  def __init__(self, job: Job) -> None: ...

class BaseExecutor(metaclass=ABCMeta):
  _scheduler: Incomplete
  _lock: Incomplete
  _logger: Incomplete
  _instances: Incomplete
  def __init__(self) -> None: ...
  def start(self, scheduler: BaseScheduler, alias: str) -> None: ...
  def shutdown(self, wait: bool = True) -> None: ...
  def submit_job(self, job: Job, run_times: list[datetime]) -> None: ...
  @abstractmethod
  def _do_submit_job(self, job: Job, run_times: list[datetime]): ...
  def _run_job_success(self, job_id: str, events) -> None: ...
  def _run_job_error(self, job_id: str, exc: Exception, traceback: TracebackType | None = None) -> None: ...

def run_job(job: Job, jobstore_alias: str, run_times: list[datetime], logger_name: str): ...
async def run_coroutine_job(job: Job, jobstore_alias: str, run_times: list[datetime], logger_name: str): ...
